# cmusic Makefile
# prepared by Victor Lazzarini, 2009

all:

	cd casslab ; make 
	cd typein; make 

clean:
	cd casslab; make clean; cd ..;
	cd typein; make clean; cd ..;

install:
	cd casslab; make install; cd ..;
	cd typein; make install; cd ..;