# define bit(x)		(1 << x)
# define D_NEW_PLAYER 	bit(0)
# define SYMTAB 	bit(1)
# define SCHED 		bit(2)
# define RUN_ARBITER	bit(3)
# define READ_STDIN	bit(4)
# define ADD_PLAYER	bit(5)
# define CYCLIST	bit(6)
# define GC		bit(7)
